// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/cs-map-preview": {
    params: {};
  };
  "/se-map-preview": {
    params: {};
  };
  "/login": {
    params: {};
  };
  "/signup": {
    params: {};
  };
  "/verify-email": {
    params: {};
  };
  "/reset-password": {
    params: {};
  };
  "/course/:courseId": {
    params: {
      "courseId": string;
    };
  };
  "/courses": {
    params: {};
  };
  "/timeline/:date": {
    params: {
      "date": string;
    };
  };
  "/event/:eventId": {
    params: {
      "eventId": string;
    };
  };
  "/profile": {
    params: {};
  };
  "/budget-planner": {
    params: {};
  };
  "/time-blocking": {
    params: {};
  };
  "/personal": {
    params: {};
  };
  "/degree-progress": {
    params: {};
  };
  "/study": {
    params: {};
  };
  "/test-sync": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/cs-map-preview" | "/se-map-preview" | "/login" | "/signup" | "/verify-email" | "/reset-password" | "/course/:courseId" | "/courses" | "/timeline/:date" | "/event/:eventId" | "/profile" | "/budget-planner" | "/time-blocking" | "/personal" | "/degree-progress" | "/study" | "/test-sync";
  };
  "routes/cs-map-preview.tsx": {
    id: "routes/cs-map-preview";
    page: "/cs-map-preview";
  };
  "routes/se-map-preview.tsx": {
    id: "routes/se-map-preview";
    page: "/se-map-preview";
  };
  "routes/login.tsx": {
    id: "routes/login";
    page: "/login";
  };
  "routes/signup.tsx": {
    id: "routes/signup";
    page: "/signup";
  };
  "routes/verify-email.tsx": {
    id: "routes/verify-email";
    page: "/verify-email";
  };
  "routes/reset-password.tsx": {
    id: "routes/reset-password";
    page: "/reset-password";
  };
  "routes/protected.tsx": {
    id: "routes/protected";
    page: "/" | "/course/:courseId" | "/courses" | "/timeline/:date" | "/event/:eventId" | "/profile" | "/budget-planner" | "/time-blocking" | "/personal" | "/degree-progress" | "/study" | "/test-sync";
  };
  "routes/home.tsx": {
    id: "routes/home";
    page: "/";
  };
  "routes/course.tsx": {
    id: "routes/course";
    page: "/course/:courseId";
  };
  "routes/courses.tsx": {
    id: "routes/courses";
    page: "/courses";
  };
  "routes/timeline.tsx": {
    id: "routes/timeline";
    page: "/timeline/:date";
  };
  "routes/event.tsx": {
    id: "routes/event";
    page: "/event/:eventId";
  };
  "routes/profile.tsx": {
    id: "routes/profile";
    page: "/profile";
  };
  "routes/budget-planner.tsx": {
    id: "routes/budget-planner";
    page: "/budget-planner";
  };
  "routes/time-blocking.tsx": {
    id: "routes/time-blocking";
    page: "/time-blocking";
  };
  "routes/personal.tsx": {
    id: "routes/personal";
    page: "/personal";
  };
  "routes/degree-progress.tsx": {
    id: "routes/degree-progress";
    page: "/degree-progress";
  };
  "routes/study.tsx": {
    id: "routes/study";
    page: "/study";
  };
  "routes/test-sync.tsx": {
    id: "routes/test-sync";
    page: "/test-sync";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/cs-map-preview": typeof import("./app/routes/cs-map-preview.tsx");
  "routes/se-map-preview": typeof import("./app/routes/se-map-preview.tsx");
  "routes/login": typeof import("./app/routes/login.tsx");
  "routes/signup": typeof import("./app/routes/signup.tsx");
  "routes/verify-email": typeof import("./app/routes/verify-email.tsx");
  "routes/reset-password": typeof import("./app/routes/reset-password.tsx");
  "routes/protected": typeof import("./app/routes/protected.tsx");
  "routes/home": typeof import("./app/routes/home.tsx");
  "routes/course": typeof import("./app/routes/course.tsx");
  "routes/courses": typeof import("./app/routes/courses.tsx");
  "routes/timeline": typeof import("./app/routes/timeline.tsx");
  "routes/event": typeof import("./app/routes/event.tsx");
  "routes/profile": typeof import("./app/routes/profile.tsx");
  "routes/budget-planner": typeof import("./app/routes/budget-planner.tsx");
  "routes/time-blocking": typeof import("./app/routes/time-blocking.tsx");
  "routes/personal": typeof import("./app/routes/personal.tsx");
  "routes/degree-progress": typeof import("./app/routes/degree-progress.tsx");
  "routes/study": typeof import("./app/routes/study.tsx");
  "routes/test-sync": typeof import("./app/routes/test-sync.tsx");
};